let assessments = [
  {
    id: 1,
    questions: [],
    title: "Bulk Assessment",
    description: "This is a sample assessment",
    total_points: 20,
    company: 1,
  },
  {
    id: 2,
    questions: [],
    title: "Bulk Assessment",
    description: "This is a sample assessment",
    total_points: 20,
    company: 1,
  },
  {
    id: 3,
    questions: [],
    title: "Bulk Assessment",
    description: "This is a sample assessment",
    total_points: 20,
    company: 1,
  },
  {
    id: 4,
    questions: [],
    title: "Bulk Assessment",
    description: "This is a sample assessment",
    total_points: 20,
    company: 1,
  },
  {
    id: 5,
    questions: [],
    title: "Bulk Assessment",
    description: "This is a sample assessment",
    total_points: 20,
    company: 1,
  },
  {
    id: 6,
    questions: [],
    title: "Bulk Assessment",
    description: "This is a sample assessment",
    total_points: 20,
    company: 1,
  },
  {
    id: 7,
    questions: [],
    title: "Bulk Assessment",
    description: "This is a sample assessment",
    total_points: 20,
    company: 1,
  },
  {
    id: 8,
    questions: [
      {
        id: 1,
        options: [],
        user_answer: [],
        question_desc: "B1?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 3,
        answer_text: "",
        assessment: 8,
      },
      {
        id: 2,
        options: [],
        user_answer: [],
        question_desc: "B2?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 4,
        answer_text: "",
        assessment: 8,
      },
    ],
    title: "Bulk Assessment",
    description: "This is a sample assessment",
    total_points: 20,
    company: 1,
  },
  {
    id: 9,
    questions: [
      {
        id: 3,
        options: [],
        user_answer: [],
        question_desc: "B1?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 3,
        answer_text: "",
        assessment: 9,
      },
      {
        id: 4,
        options: [],
        user_answer: [],
        question_desc: "B2?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 4,
        answer_text: "",
        assessment: 9,
      },
    ],
    title: "Bulk Assessment",
    description: "This is a sample assessment",
    total_points: 20,
    company: 1,
  },
  {
    id: 10,
    questions: [
      {
        id: 5,
        options: [],
        user_answer: [],
        question_desc: "B1?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 3,
        answer_text: "",
        assessment: 10,
      },
      {
        id: 6,
        options: [],
        user_answer: [],
        question_desc: "B2?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 4,
        answer_text: "",
        assessment: 10,
      },
    ],
    title: "Bulk Assessment",
    description: "This is a sample assessment",
    total_points: 20,
    company: 1,
  },
  {
    id: 11,
    questions: [
      {
        id: 7,
        options: [],
        user_answer: [],
        question_desc: "B1?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 3,
        answer_text: "",
        assessment: 11,
      },
      {
        id: 8,
        options: [],
        user_answer: [],
        question_desc: "B2?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 4,
        answer_text: "",
        assessment: 11,
      },
    ],
    title: "Bulk Assessment",
    description: "This is a sample assessment",
    total_points: 20,
    company: 1,
  },
  {
    id: 12,
    questions: [
      {
        id: 9,
        options: [],
        user_answer: [],
        question_desc: "B1?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 3,
        answer_text: "",
        assessment: 12,
      },
      {
        id: 10,
        options: [],
        user_answer: [],
        question_desc: "B2?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 4,
        answer_text: "",
        assessment: 12,
      },
    ],
    title: "Bulk Assessment",
    description: "This is a sample assessment",
    total_points: 20,
    company: 1,
  },
  {
    id: 13,
    questions: [
      {
        id: 11,
        options: [],
        user_answer: [],
        question_desc: "B1?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 3,
        answer_text: "",
        assessment: 13,
      },
      {
        id: 12,
        options: [],
        user_answer: [],
        question_desc: "B2?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 4,
        answer_text: "",
        assessment: 13,
      },
    ],
    title: "Bulk Assessment",
    description: "This is a sample assessment",
    total_points: 20,
    company: 1,
  },
  {
    id: 14,
    questions: [
      {
        id: 13,
        options: [],
        user_answer: [],
        question_desc: "B1?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 3,
        answer_text: "",
        assessment: 14,
      },
      {
        id: 14,
        options: [],
        user_answer: [],
        question_desc: "B2?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 4,
        answer_text: "",
        assessment: 14,
      },
    ],
    title: "Bulk Assessment",
    description: "This is a sample assessment",
    total_points: 20,
    company: 1,
  },
  {
    id: 15,
    questions: [
      {
        id: 15,
        options: [],
        user_answer: [],
        question_desc: "B1?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 3,
        answer_text: "",
        assessment: 15,
      },
      {
        id: 16,
        options: [],
        user_answer: [],
        question_desc: "B2?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 4,
        answer_text: "",
        assessment: 15,
      },
    ],
    title: "Bulk Assessment",
    description: "This is a sample assessment",
    total_points: 20,
    company: 1,
  },
  {
    id: 16,
    questions: [
      {
        id: 17,
        options: [],
        user_answer: [],
        question_desc: "B1?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 3,
        answer_text: "",
        assessment: 16,
      },
      {
        id: 18,
        options: [],
        user_answer: [],
        question_desc: "B2?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 4,
        answer_text: "",
        assessment: 16,
      },
    ],
    title: "Bulk Assessment",
    description: "This is a sample assessment",
    total_points: 20,
    company: 1,
  },
  {
    id: 17,
    questions: [
      {
        id: 19,
        options: [],
        user_answer: [],
        question_desc: "B1?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 3,
        answer_text: "",
        assessment: 17,
      },
      {
        id: 20,
        options: [],
        user_answer: [],
        question_desc: "B2?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 4,
        answer_text: "",
        assessment: 17,
      },
    ],
    title: "Bulk Assessment",
    description: "This is a sample assessment",
    total_points: 20,
    company: 1,
  },
  {
    id: 18,
    questions: [
      {
        id: 21,
        options: [],
        user_answer: [],
        question_desc: "B1?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 3,
        answer_text: "",
        assessment: 18,
      },
      {
        id: 22,
        options: [],
        user_answer: [],
        question_desc: "B2?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 4,
        answer_text: "",
        assessment: 18,
      },
    ],
    title: "Bulk Assessment",
    description: "This is a sample assessment",
    total_points: 20,
    company: 1,
  },
  {
    id: 19,
    questions: [
      {
        id: 23,
        options: [],
        user_answer: [],
        question_desc: "B1?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 3,
        answer_text: "",
        assessment: 19,
      },
      {
        id: 24,
        options: [],
        user_answer: [],
        question_desc: "B2?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 4,
        answer_text: "",
        assessment: 19,
      },
    ],
    title: "Bulk Assessment",
    description: "This is a sample assessment",
    total_points: 20,
    company: 1,
  },
  {
    id: 20,
    questions: [
      {
        id: 25,
        options: [
          {
            id: 1,
            option_text: "Madrid",
            question: 25,
          },
        ],
        user_answer: [],
        question_desc: "B1?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 3,
        answer_text: "",
        assessment: 20,
      },
      {
        id: 26,
        options: [
          {
            id: 2,
            option_text: "Rome",
            question: 26,
          },
        ],
        user_answer: [
          {
            id: 1,
            obtained_points: 2,
            answer_text: "This is the answer for question 1.",
            candidate: 1,
            question: 26,
          },
          {
            id: 3,
            obtained_points: 5,
            answer_text: "1st updated answer",
            candidate: 1,
            question: 26,
          },
          {
            id: 4,
            obtained_points: 2,
            answer_text: "This is the answer for question 1.",
            candidate: 1,
            question: 26,
          },
          {
            id: 7,
            obtained_points: 2,
            answer_text: "This is the answer for question 1.",
            candidate: 1,
            question: 26,
          },
          {
            id: 10,
            obtained_points: 2,
            answer_text: "This is the answer for question 1.",
            candidate: 1,
            question: 26,
          },
        ],
        question_desc: "B2?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 4,
        answer_text: "",
        assessment: 20,
      },
      {
        id: 27,
        options: [
          {
            id: 3,
            option_text: "Lahore",
            question: 27,
          },
        ],
        user_answer: [
          {
            id: 2,
            obtained_points: 3,
            answer_text: "This is the answer for question 2.",
            candidate: 1,
            question: 27,
          },
          {
            id: 5,
            obtained_points: 3,
            answer_text: "This is the answer for question 2.",
            candidate: 1,
            question: 27,
          },
          {
            id: 8,
            obtained_points: 3,
            answer_text: "This is the answer for question 2.",
            candidate: 1,
            question: 27,
          },
          {
            id: 11,
            obtained_points: 3,
            answer_text: "This is the answer for question 2.",
            candidate: 1,
            question: 27,
          },
        ],
        question_desc: "NUST?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 3,
        answer_text: "",
        assessment: 20,
      },
      {
        id: 28,
        options: [
          {
            id: 4,
            option_text: "Italy",
            question: 28,
          },
        ],
        user_answer: [
          {
            id: 6,
            obtained_points: 1,
            answer_text: "This is the answer for question 3.",
            candidate: 1,
            question: 28,
          },
          {
            id: 9,
            obtained_points: 1,
            answer_text: "This is the answer for question 3.",
            candidate: 1,
            question: 28,
          },
          {
            id: 12,
            obtained_points: 1,
            answer_text: "This is the answer for question 3.",
            candidate: 1,
            question: 28,
          },
        ],
        question_desc: "NUTS?",
        question_type: "MCQ",
        question_point: 2,
        number_of_options: 4,
        answer_text: "",
        assessment: 20,
      },
    ],
    title: "Bulk Assessment",
    description: "This is a sample assessment",
    total_points: 20,
    company: 1,
  },
];

export default assessments;
